<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OldSchoolForms.Ui.Designer</RootNamespace>
    <AssemblyName>OldSchoolForms.Ui.Designer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\OldSchoolForms.Ui\OldSchoolForms.Ui.csproj" />
  </ItemGroup>
</Project>
