<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OldSchoolFormsUiApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OldSchoolForms.Ui" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(useWebBrowser)' == 'true'">
    <PackageReference Include="OldSchoolForms.Ui.WebBrowser" Version="0.1.0" />
  </ItemGroup>

</Project>
