<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CoreForms.Ui</RootNamespace>
    <AssemblyName>CoreForms.Ui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreForms.Ui.Sdl\CoreForms.Ui.Sdl.csproj" />
  </ItemGroup>

</Project>