<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CoreForms.Ui.WebBrowser</RootNamespace>
    <AssemblyName>CoreForms.Ui.WebBrowser</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreForms.Ui\CoreForms.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefGlue.Common" Version="120.6099.211" />
  </ItemGroup>

</Project>