using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using OldSchoolForms.Ui.Core;
using OldSchoolForms.Ui.Designer;
using OldSchoolForms.Ui.Designer.Services;

namespace OldSchoolForms.Ui.Designer.Roslyn;

/// <summary>
/// Generates C# code for a Windows Forms-style InitializeComponent method
/// based on the controls placed on a <see cref="DesignSurface"/>.
/// </summary>
public class CodeGenerator
{
    private readonly DesignSurface _surface;
    private const string GeneratedClassName = "InitializeComponent";

    // C# keywords that can never be used as a field name without escaping.
    private static readonly HashSet<string> ReservedKeywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked",
        "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else",
        "enum", "event", "explicit", "extern", "false", "finally", "fixed", "float", "for",
        "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock",
        "long", "namespace", "new", "null", "object", "operator", "out", "override", "params",
        "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short",
        "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true",
        "try", "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using", "virtual",
        "void", "volatile", "while", "var", "global", "dynamic", "dyn"
    };

    // Property names emitted for every control; a field sharing one of these would hide the
    // inherited property and break the generated assignments.
    private static readonly HashSet<string> ReservedPropertyNames = new(StringComparer.Ordinal)
    {
        "Location", "Size", "Text", "Name", "BackColor", "TabIndex", "TabStop", "Enabled", "Visible"
    };

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeGenerator"/> class.
    /// </summary>
    /// <param name="surface">The design surface to generate code for.</param>
    /// <exception cref="ArgumentNullException">Thrown if surface is null.</exception>
    public CodeGenerator(DesignSurface surface)
    {
        _surface = surface ?? throw new ArgumentNullException(nameof(surface));
    }

    /// <summary>
    /// Generates the complete InitializeComponent method for the designed form.
    /// </summary>
    /// <param name="namespaceName">The namespace for the generated partial class.</param>
    /// <param name="className">The class name of the form.</param>
    /// <returns>A string containing the complete generated code.</returns>
    public string Generate(string namespaceName, string className)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by the OldSchoolForms Form Designer.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using OldSchoolForms.Ui.Core;");
        sb.AppendLine("using OldSchoolForms.Ui.Controls.Basic;");
        sb.AppendLine("using OldSchoolForms.Ui.Controls.Containers;");
        sb.AppendLine("using OldSchoolForms.Ui.Controls.Advanced;");
        sb.AppendLine("using OldSchoolForms.Ui.Layout;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        var indent = !string.IsNullOrEmpty(namespaceName) ? "    " : "";
        sb.AppendLine($"{indent}partial class {className}");
        sb.AppendLine($"{indent}{{");

        var subIndent = indent + "    ";

        // Resolve a guaranteed-unique field name for every control once, so the four
        // generation passes below never emit duplicate variable names.
        var fieldNameMap = BuildFieldNameMap(className);

        // Field declarations
        foreach (var item in _surface.Items)
        {
            if (item.Control == _surface.RootControl) continue;
            var control = item.Control;
            string typeName = control.GetType().Name;
            string fieldName = fieldNameMap[control];
            sb.AppendLine($"{subIndent}private {typeName} {fieldName};");
        }

        sb.AppendLine();

        // InitializeComponent method
        sb.AppendLine($"{subIndent}private void {GeneratedClassName}()");
        sb.AppendLine($"{subIndent}{{");

        var bodyIndent = subIndent + "    ";

        // Create control instances
        foreach (var item in _surface.Items)
        {
            if (item.Control == _surface.RootControl) continue;
            var control = item.Control;
            string fieldName = fieldNameMap[control];
            string typeName = control.GetType().Name;
            sb.AppendLine($"{bodyIndent}{fieldName} = new {typeName}();");
        }

        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}SuspendLayout();");

        // Configure each control
        foreach (var item in _surface.Items)
        {
            if (item.Control == _surface.RootControl) continue;
            var control = item.Control;
            string fieldName = fieldNameMap[control];

            sb.AppendLine();
            sb.AppendLine($"{bodyIndent}//");
            sb.AppendLine($"{bodyIndent}// {fieldName}");
            sb.AppendLine($"{bodyIndent}//");

            GeneratePropertyAssignments(sb, bodyIndent, control, fieldName);
        }

        // Controls.Add hierarchy
        GenerateControlHierarchy(sb, bodyIndent, _surface, fieldNameMap);

        sb.AppendLine($"{bodyIndent}ResumeLayout(false);");
        sb.AppendLine($"{subIndent}}}");

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GeneratePropertyAssignments(StringBuilder sb, string indent, Control control, string fieldName)
    {
        var props = new (string Name, Func<string?> Value)[]
        {
            ("Location", () => FormatPoint(control.Location)),
            ("Size", () => FormatSize(control.Size)),
            ("Text", () => Quote(control.Text)),
            ("Name", () => Quote(control.Name)),
            ("BackColor", () => FormatColor(control.BackColor)),
            ("TabIndex", () => control.TabIndex.ToString()),
            ("TabStop", () => control.TabStop.ToLowerString()),
            ("Enabled", () => control.Enabled.ToLowerString()),
            ("Visible", () => control.Visible.ToLowerString()),
        };

        foreach (var (propName, valueFn) in props)
        {
            var value = valueFn();
            if (!string.IsNullOrEmpty(value))
            {
                sb.AppendLine($"{indent}{fieldName}.{propName} = {value};");
            }
        }
    }

    private static void GenerateControlHierarchy(
        StringBuilder sb,
        string indent,
        DesignSurface surface,
        IReadOnlyDictionary<Control, string> fieldNameMap)
    {
        sb.AppendLine();
        sb.AppendLine($"{indent}// Control hierarchy");
        sb.AppendLine();

        // For simplicity, generate Controls.Add for all items at root level
        foreach (var item in surface.Items)
        {
            if (item.Control == surface.RootControl) continue;
            var control = item.Control;
            string fieldName = fieldNameMap[control];
            Control? parent = control.Parent;

            if (parent != null && parent != surface && parent != surface.RootControl)
            {
                string parentField = fieldNameMap[parent];
                sb.AppendLine($"{indent}{parentField}.Controls.Add({fieldName});");
            }
            else
            {
                sb.AppendLine($"{indent}Controls.Add({fieldName});");
            }
        }
    }

    /// <summary>
    /// Resolves a guaranteed-unique, valid C# field name for every non-root control on the
    /// surface. The same map is reused by all generation passes so field names never diverge
    /// or collide between the field declarations, instantiations, property assignments and the
    /// control hierarchy.
    /// </summary>
    /// <param name="className">The name of the partial class being generated, reserved so a
    /// control can never shadow the class itself.</param>
    /// <returns>A mapping from each designed control to its unique field name.</returns>
    private Dictionary<Control, string> BuildFieldNameMap(string className)
    {
        var reserved = new HashSet<string>(ReservedKeywords, StringComparer.Ordinal);
        reserved.Add(GeneratedClassName);
        foreach (var property in ReservedPropertyNames)
            reserved.Add(property);
        if (!string.IsNullOrEmpty(className))
            reserved.Add(className);

        var map = new Dictionary<Control, string>();
        foreach (var item in _surface.Items)
        {
            if (item.Control == _surface.RootControl) continue;
            map[item.Control] = BuildUniqueName(item.Control, reserved);
        }
        return map;
    }

    /// <summary>
    /// Assigns the next unused name for the given control, suffixing an incrementing counter
    /// on every collision (e.g. <c>button</c>, <c>button1</c>, <c>button2</c>).
    /// </summary>
    /// <param name="control">The control to name.</param>
    /// <param name="reserved">The set of names already taken or otherwise forbidden.</param>
    /// <returns>The unique field name for the control.</returns>
    private static string BuildUniqueName(Control control, HashSet<string> reserved)
    {
        string baseName = SanitizeIdentifier(ResolveBaseName(control));
        if (string.IsNullOrEmpty(baseName))
            baseName = "control";

        string name = baseName;
        int counter = 1;
        while (!reserved.Add(name))
            name = $"{baseName}{counter++}";

        return name;
    }

    /// <summary>
    /// Determines the preferred base name for a control: its <see cref="Control.Name"/> when
    /// set, otherwise the lower-cased type name (e.g. <c>Button</c> -&gt; <c>button</c>).
    /// </summary>
    /// <param name="control">The control to name.</param>
    /// <returns>The preferred, pre-sanitization base name.</returns>
    private static string ResolveBaseName(Control control)
    {
        if (!string.IsNullOrWhiteSpace(control.Name))
            return control.Name;

        // Generate a name based on type
        string typeName = control.GetType().Name;
        if (typeName.Length == 0)
            return typeName;
        return char.ToLowerInvariant(typeName[0]) + typeName[1..];
    }

    /// <summary>
    /// Converts an arbitrary string into a legal C# identifier by replacing illegal characters
    /// with underscores and prefixing an underscore when the result would otherwise start with a
    /// digit. An empty input yields an empty string.
    /// </summary>
    /// <param name="name">The raw name to sanitize.</param>
    /// <returns>A syntactically valid C# identifier, or an empty string when <paramref name="name"/>
    /// is null or empty.</returns>
    private static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
            return string.Empty;

        var chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            bool identifierChar = char.IsLetterOrDigit(chars[i]) || chars[i] == '_';
            if (!identifierChar)
                chars[i] = '_';
        }

        string result = new string(chars);
        if (char.IsDigit(result[0]))
            result = "_" + result;
        return result;
    }

    private static string FormatPoint(Point p) => $"new Point({p.X}, {p.Y})";
    private static string FormatSize(Size s) => $"new Size({s.Width}, {s.Height})";
    private static string FormatColor(Color c)
    {
        // Emit named color references when they match known colors
        if (c.A == 255)
        {
            if (c == Color.White) return "Color.White";
            if (c == Color.Black) return "Color.Black";
            if (c == Color.Red) return "Color.Red";
            if (c == Color.Green) return "Color.Green";
            if (c == Color.Blue) return "Color.Blue";
            if (c == Color.Yellow) return "Color.Yellow";
            if (c == Color.Transparent) return "Color.Transparent";

            // SystemColors — resolved at runtime, not fixed RGB
            if (c == SystemColors.Control) return "SystemColors.Control";
            if (c == SystemColors.ControlText) return "SystemColors.ControlText";
            if (c == SystemColors.Window) return "SystemColors.Window";
            if (c == SystemColors.WindowText) return "SystemColors.WindowText";
            if (c == SystemColors.Highlight) return "SystemColors.Highlight";
            if (c == SystemColors.HighlightText) return "SystemColors.HighlightText";
            if (c == SystemColors.ActiveCaption) return "SystemColors.ActiveCaption";
            if (c == SystemColors.ActiveCaptionText) return "SystemColors.ActiveCaptionText";
            if (c == SystemColors.InactiveCaption) return "SystemColors.InactiveCaption";
            if (c == SystemColors.ControlLight) return "SystemColors.ControlLight";
            if (c == SystemColors.ControlDark) return "SystemColors.ControlDark";
            if (c == SystemColors.GrayText) return "SystemColors.GrayText";
        }
        else
        {
            if (c == Color.Transparent) return "Color.Transparent";
            if (c == Color.Empty) return "Color.Empty";
        }

        // Fall back to RGB for custom colors
        return $"Color.FromArgb({c.R}, {c.G}, {c.B}{(c.A < 255 ? $", {c.A}" : "")})";
    }
    private static string Quote(string s) => string.IsNullOrEmpty(s) ? "" : $"\"{EscapeString(s)}\"";
    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
}

internal static class BoolExtensions
{
    public static string ToLowerString(this bool value) => value ? "true" : "false";
}
