using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using CoreForms.Ui.Core;
using CoreForms.Ui.Designer;
using CoreForms.Ui.Designer.Services;

namespace CoreForms.Ui.Designer.Roslyn;

/// <summary>
/// Generates C# code for a Windows Forms-style InitializeComponent method
/// based on the controls placed on a <see cref="DesignSurface"/>.
/// </summary>
public class CodeGenerator
{
    private readonly DesignSurface _surface;
    private const string GeneratedClassName = "InitializeComponent";

    /// <summary>
    /// Initializes a new instance of the <see cref="CodeGenerator"/> class.
    /// </summary>
    /// <param name="surface">The design surface to generate code for.</param>
    /// <exception cref="ArgumentNullException">Thrown if surface is null.</exception>
    public CodeGenerator(DesignSurface surface)
    {
        _surface = surface ?? throw new ArgumentNullException(nameof(surface));
    }

    /// <summary>
    /// Generates the complete InitializeComponent method for the designed form.
    /// </summary>
    /// <param name="namespaceName">The namespace for the generated partial class.</param>
    /// <param name="className">The class name of the form.</param>
    /// <returns>A string containing the complete generated code.</returns>
    public string Generate(string namespaceName, string className)
    {
        var sb = new StringBuilder();

        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("//     This code was generated by the CoreForms Form Designer.");
        sb.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        sb.AppendLine("//     the code is regenerated.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("//------------------------------------------------------------------------------");
        sb.AppendLine();
        sb.AppendLine("using CoreForms.Ui.Core;");
        sb.AppendLine("using CoreForms.Ui.Controls.Basic;");
        sb.AppendLine("using CoreForms.Ui.Controls.Containers;");
        sb.AppendLine("using CoreForms.Ui.Controls.Advanced;");
        sb.AppendLine("using CoreForms.Ui.Layout;");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        var indent = !string.IsNullOrEmpty(namespaceName) ? "    " : "";
        sb.AppendLine($"{indent}partial class {className}");
        sb.AppendLine($"{indent}{{");

        var subIndent = indent + "    ";

        // Field declarations
        foreach (var item in _surface.Items)
        {
            var control = item.Control;
            string typeName = control.GetType().Name;
            string fieldName = GetFieldName(control);
            sb.AppendLine($"{subIndent}private {typeName} {fieldName};");
        }

        sb.AppendLine();

        // InitializeComponent method
        sb.AppendLine($"{subIndent}private void {GeneratedClassName}()");
        sb.AppendLine($"{subIndent}{{");

        var bodyIndent = subIndent + "    ";

        // Create control instances
        foreach (var item in _surface.Items)
        {
            var control = item.Control;
            string fieldName = GetFieldName(control);
            string typeName = control.GetType().Name;
            sb.AppendLine($"{bodyIndent}{fieldName} = new {typeName}();");
        }

        sb.AppendLine();
        sb.AppendLine($"{bodyIndent}SuspendLayout();");

        // Configure each control
        foreach (var item in _surface.Items)
        {
            var control = item.Control;
            string fieldName = GetFieldName(control);

            sb.AppendLine();
            sb.AppendLine($"{bodyIndent}//");
            sb.AppendLine($"{bodyIndent}// {fieldName}");
            sb.AppendLine($"{bodyIndent}//");

            GeneratePropertyAssignments(sb, bodyIndent, control, fieldName);
        }

        // Controls.Add hierarchy
        GenerateControlHierarchy(sb, bodyIndent, _surface);

        sb.AppendLine($"{bodyIndent}ResumeLayout(false);");
        sb.AppendLine($"{subIndent}}}");

        sb.AppendLine($"{indent}}}");

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void GeneratePropertyAssignments(StringBuilder sb, string indent, Control control, string fieldName)
    {
        var props = new (string Name, Func<string?> Value)[]
        {
            ("Location", () => FormatPoint(control.Location)),
            ("Size", () => FormatSize(control.Size)),
            ("Text", () => Quote(control.Text)),
            ("Name", () => Quote(control.Name)),
            ("BackColor", () => FormatColor(control.BackColor)),
            ("TabIndex", () => control.TabIndex.ToString()),
            ("TabStop", () => control.TabStop.ToLowerString()),
            ("Enabled", () => control.Enabled.ToLowerString()),
            ("Visible", () => control.Visible.ToLowerString()),
        };

        foreach (var (propName, valueFn) in props)
        {
            var value = valueFn();
            if (!string.IsNullOrEmpty(value))
            {
                sb.AppendLine($"{indent}{fieldName}.{propName} = {value};");
            }
        }
    }

    private static void GenerateControlHierarchy(StringBuilder sb, string indent, DesignSurface surface)
    {
        sb.AppendLine();
        sb.AppendLine($"{indent}// Control hierarchy");
        sb.AppendLine();

        // For simplicity, generate Controls.Add for all items at root level
        foreach (var item in surface.Items)
        {
            var control = item.Control;
            string fieldName = GetFieldName(control);
            Control? parent = control.Parent;

            if (parent != null && parent != surface)
            {
                string parentField = GetFieldName(parent);
                sb.AppendLine($"{indent}{parentField}.Controls.Add({fieldName});");
            }
            else
            {
                sb.AppendLine($"{indent}Controls.Add({fieldName});");
            }
        }
    }

    private static string GetFieldName(Control control)
    {
        if (!string.IsNullOrEmpty(control.Name))
            return control.Name;

        // Generate a name based on type
        string baseName = control.GetType().Name;
        return char.ToLowerInvariant(baseName[0]) + baseName[1..];
    }

    private static string FormatPoint(Point p) => $"new Point({p.X}, {p.Y})";
    private static string FormatSize(Size s) => $"new Size({s.Width}, {s.Height})";
    private static string FormatColor(Color c)
    {
        // Emit named color references when they match known colors
        if (c.A == 255)
        {
            if (c == Color.White) return "Color.White";
            if (c == Color.Black) return "Color.Black";
            if (c == Color.Red) return "Color.Red";
            if (c == Color.Green) return "Color.Green";
            if (c == Color.Blue) return "Color.Blue";
            if (c == Color.Yellow) return "Color.Yellow";
            if (c == Color.Transparent) return "Color.Transparent";

            // SystemColors — resolved at runtime, not fixed RGB
            if (c == SystemColors.Control) return "SystemColors.Control";
            if (c == SystemColors.ControlText) return "SystemColors.ControlText";
            if (c == SystemColors.Window) return "SystemColors.Window";
            if (c == SystemColors.WindowText) return "SystemColors.WindowText";
            if (c == SystemColors.Highlight) return "SystemColors.Highlight";
            if (c == SystemColors.HighlightText) return "SystemColors.HighlightText";
            if (c == SystemColors.ActiveCaption) return "SystemColors.ActiveCaption";
            if (c == SystemColors.ActiveCaptionText) return "SystemColors.ActiveCaptionText";
            if (c == SystemColors.InactiveCaption) return "SystemColors.InactiveCaption";
            if (c == SystemColors.ControlLight) return "SystemColors.ControlLight";
            if (c == SystemColors.ControlDark) return "SystemColors.ControlDark";
            if (c == SystemColors.GrayText) return "SystemColors.GrayText";
        }
        else
        {
            if (c == Color.Transparent) return "Color.Transparent";
            if (c == Color.Empty) return "Color.Empty";
        }

        // Fall back to RGB for custom colors
        return $"Color.FromArgb({c.R}, {c.G}, {c.B}{(c.A < 255 ? $", {c.A}" : "")})";
    }
    private static string Quote(string s) => string.IsNullOrEmpty(s) ? "" : $"\"{EscapeString(s)}\"";
    private static string EscapeString(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r").Replace("\t", "\\t");
}

internal static class BoolExtensions
{
    public static string ToLowerString(this bool value) => value ? "true" : "false";
}
