using System;
using System.IO;
using CoreForms.Ui.Designer;

namespace CoreForms.Ui.Designer.Roslyn;

/// <summary>
/// Manages the pair of source files for a designed form:
/// the user-code file (Form.cs) and the auto-generated designer file (Form.Designer.cs).
/// Handles loading, saving, and merging of generated code with user code.
/// </summary>
public class DesignerFileManager
{
    /// <summary>
    /// Gets the path to the user-code file (e.g., MainForm.cs).
    /// </summary>
    public string UserCodePath { get; }

    /// <summary>
    /// Gets the path to the auto-generated designer file (e.g., MainForm.Designer.cs).
    /// </summary>
    public string DesignerCodePath { get; }

    /// <summary>
    /// Gets or sets the namespace of the form class.
    /// </summary>
    public string Namespace { get; set; } = "CoreForms.Ui.Demo";

    /// <summary>
    /// Gets or sets the class name of the form.
    /// </summary>
    public string ClassName { get; set; } = "MainForm";

    /// <summary>
    /// Initializes a new instance of the <see cref="DesignerFileManager"/> class.
    /// </summary>
    /// <param name="userCodePath">Path to the user code file (.cs).</param>
    /// <exception cref="ArgumentNullException">Thrown if userCodePath is null.</exception>
    public DesignerFileManager(string userCodePath)
    {
        UserCodePath = userCodePath ?? throw new ArgumentNullException(nameof(userCodePath));

        // Derive designer file path: e.g., MainForm.cs → MainForm.Designer.cs
        string directory = Path.GetDirectoryName(userCodePath) ?? ".";
        string fileNameWithoutExt = Path.GetFileNameWithoutExtension(userCodePath);
        string extension = Path.GetExtension(userCodePath);
        DesignerCodePath = Path.Combine(directory, $"{fileNameWithoutExt}.Designer{extension}");
    }

    /// <summary>
    /// Loads the designer file and populates the design surface.
    /// Returns a list of warnings from the parser.
    /// </summary>
    /// <param name="surface">The design surface to populate.</param>
    /// <returns>A list of parse warnings, or an empty list if none.</returns>
    public System.Collections.Generic.List<string> Load(DesignSurface surface)
    {
        if (!File.Exists(DesignerCodePath))
            throw new FileNotFoundException("Designer file not found.", DesignerCodePath);

        string source = File.ReadAllText(DesignerCodePath);
        var parser = new FormParser();
        return parser.Parse(source, surface);
    }

    /// <summary>
    /// Saves the current design surface state to the designer file.
    /// </summary>
    /// <param name="surface">The design surface to save.</param>
    public void Save(DesignSurface surface)
    {
        string directory = Path.GetDirectoryName(DesignerCodePath) ?? ".";
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        var generator = new CodeGenerator(surface);
        string code = generator.Generate(Namespace, ClassName);
        File.WriteAllText(DesignerCodePath, code);
    }

    /// <summary>
    /// Creates a new designer file pair (user code + designer file) at the given path.
    /// </summary>
    /// <param name="userCodePath">The path for the user code file.</param>
    /// <param name="namespaceName">The namespace for the new form.</param>
    /// <param name="className">The class name for the new form.</param>
    /// <returns>A new DesignerFileManager for the created files.</returns>
    public static DesignerFileManager CreateNew(string userCodePath, string namespaceName, string className)
    {
        string directory = Path.GetDirectoryName(userCodePath) ?? ".";
        if (!Directory.Exists(directory))
            Directory.CreateDirectory(directory);

        string fileNameWithoutExt = Path.GetFileNameWithoutExtension(userCodePath);
        string extension = Path.GetExtension(userCodePath);
        string designerPath = Path.Combine(directory, $"{fileNameWithoutExt}.Designer{extension}");

        // Create user code file with partial class
        string userCode = $$"""
// <auto-generated>
// This file contains user code for the {{className}} form.
// </auto-generated>

namespace {{namespaceName}}
{
    partial class {{className}}
    {
        public {{className}}()
        {
            InitializeComponent();
        }
    }
}
""";
        File.WriteAllText(userCodePath, userCode);

        // Create designer file (minimal stub)
        string designerCode = $$"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the CoreForms Form Designer.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace {{namespaceName}}
{
    partial class {{className}}
    {
        private void InitializeComponent()
        {
            SuspendLayout();
            ResumeLayout(false);
        }
    }
}
""";
        File.WriteAllText(designerPath, designerCode);

        return new DesignerFileManager(userCodePath)
        {
            Namespace = namespaceName,
            ClassName = className
        };
    }
}
