<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OldSchoolForms.Ui.WebBrowser</RootNamespace>
    <AssemblyName>OldSchoolForms.Ui.WebBrowser</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>0.1.0</Version>
    <Authors>Hagen Siegel</Authors>
    <Description>WebView Control for OldSchoolForms-Apps</Description>
    <Copyright>Copyright (c) 2026 Hagen Siegel</Copyright>
    <PackageProjectUrl>https://github.com/theRainbird/OldSchoolForms</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/theRainbird/OldSchoolForms/blob/silk/LICENSE</PackageLicenseUrl>
    <PackageIcon>OldSchoolForms-NuGetIcon.png</PackageIcon>
    <RepositoryUrl>https://github.com/theRainbird/OldSchoolForms/tree/silk/src/OldSchoolForms.Ui.WebBrowser</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Forms, WebBrowser, Control, Browser, Linux</PackageTags>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.o</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OldSchoolForms.Ui\OldSchoolForms.Ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefGlue.Common" Version="120.6099.211" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\OldSchoolForms.Ui\Resources\Icons\OldSchoolForms-NuGetIcon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
      <Link>OldSchoolForms-NuGetIcon.png</Link>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>$(DefineConstants);WINDOWS</DefineConstants>
  </PropertyGroup>

</Project>