<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CoreForms.Ui.Sdl</RootNamespace>
    <AssemblyName>CoreForms.Ui.Sdl</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.SDL" Version="2.21.0" />
  </ItemGroup>

</Project>