name: .NET Build and Test

on:
  push:
    branches: [ "silk" ]
  pull_request:
    branches: [ "silk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore core library
      run: dotnet restore src/OldSchoolForms.Ui/OldSchoolForms.Ui.csproj

    - name: Build core library
      run: dotnet build src/OldSchoolForms.Ui/OldSchoolForms.Ui.csproj --no-restore -c ${{ matrix.configuration }}

    - name: Restore tests
      run: dotnet restore tests/OldSchoolForms.Ui.Tests/OldSchoolForms.Ui.Tests.csproj

    - name: Build and run tests
      run: dotnet test tests/OldSchoolForms.Ui.Tests/OldSchoolForms.Ui.Tests.csproj -c ${{ matrix.configuration }} --logger "trx;LogFileName=test.trx"
