name: .NET Build and Test

on:
  push:
    branches: [ "silk" ]
  pull_request:
    branches: [ "silk" ]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Path: OldSchoolForms.Ui.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Path

    - name: Build
      run: dotnet build $env:Solution_Path --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
